### ISSUE TITLE
FR: Do not load the scripts into the text editor

### ISSUE THREAD

**Issue by gerroon** [RivinHD/ScriptToButton#2]
Hi

Is it possible to not to load the saved button scripts in the new sessions of Blender unless the user want sto edit them? Loading al those scripts can make the script editor listing a bit polluted. This can be an issue when the scenes are shared with other people where they wont have thew script and Blender might throw errors for not finding the scripts, assuming that it does references them from the disk now.

Thanks

**Comment by RivinHD** [comment]
Hi 

Thanks for your suggestion.
Do I understand you right?
You want an option to load the scripts in the "script editor" to edit them.

The problem is that the script needs to be loaded in the editor to run the scripts of the pressed button. The scripts need to be in the Blender Environment to access the bpy module.
I could implement this in 2 ways:
1. The scripts will be loaded in the editor if you want to edit them or if the button of the script get pressed
2. The scripts will be only loaded in the editor if you want to edit them. If the button is pressed the script get loaded into the editor from the disk, executed with the settings and deleted after the script finished.

Which way should I implement?
I will add this then in the next Update of Script To Button

**Comment by gerroon** [comment]
Hi

Thanks for considering it.

I personally prefer that it is removed from the text editor after the execution, this should be as transparent as possible. Obviously it is also nice to be able to edit the script on demand.

**Comment by RivinHD** [comment]
Ok, thanks for your answer.

I will implement an option to not load the script on start to the editor and also an option to load the script temporary in the editor to execute it (and then delete it after usage).

**Comment by RivinHD** [comment]
Update is finished.
Sorry for the long wait.

**Comment by gerroon** [comment]
Hey thanks I will give it a try

**Comment by gerroon** [comment]
Hi

It does not seem to work for me. Neither removing it from the text block nor running a button script works.

I also see that it is trying to do updates and failing since my desktop is not connected

```
HTTPSConnectionPool(host='api.github.com', port=443): Max retries exceeded with url: /repos/RivinHD/ScriptToButton/contents/__init__.py (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000002AA84AC8B08>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

```

**Comment by RivinHD** [comment]
The connection error is normal. If no Connection is available it is shown and detailed information of the Error is printed in the Console.
The bug is fixed. I will upload it in 2.1.1. You can update with the Update function this should work. I have tested it extensively.

**Comment by RivinHD** [comment]
I will add that the reload function will automatically load it into the Texteditor and remove it again if it has to be loaded in

**Comment by gerroon** [comment]
Hi

Thanks for the fix it seems to work now.
